=== things-library/Schemas/latest/library.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://schema.thingslibrary.io/1.0/library.json",
    "$comment": "Libraries hold item types and items that have a type.",

    "$defs": {
        "item-type": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "title": "Name",
                    "minLength": 1,
                    "maxLength": 50
                },

                "rev": {
                    "type": "integer",
                    "title": "Revision",
                    "minimum": 0,
                    "default": 0
                },

                "tags": {
                    "type": "object",
                    "title": "Attributes",
                    "patternProperties": {
                        "^[a-z0-9_-]{1,50}$": {
                            "$ref": "#/$defs/item-type-attribute"
                        }
                    },
                    "additionalProperties": false
                },

                "items": {
                    "type": "object",
                    "title": "Attachments",
                    "patternProperties": {
                        "^[a-z0-9_-]{1,50}$": {
                            "$ref": "#/$defs/item-type-attachment"
                        }
                    },
                    "additionalProperties": false
                },

                "meta": {
                    "type": "object",
                    "title": "Metadata",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            },
            "additionalProperties": false,
            "required": [ "name" ]
        },

        "item-type-attachment": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "title": "Type",
                    "minLength": 1,
                    "maxLength": 50,
                    "pattern": "^[a-z0-9_-]{1,50}$"
                },

                "name": {
                    "type": "string",
                    "title": "Name",
                    "minLength": 1,
                    "maxLength": 50
                },

                "revision": {
                    "type": "integer",
                    "title": "Revision",
                    "minimum": 0,
                    "default": 0
                },

                "meta": {
                    "type": "object",
                    "title": "Metadata",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            },
            "additionalProperties": false,
            "required": [ "type", "name" ]
        },

        "item-type-attribute": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "title": "Name",
                    "minLength": 1,
                    "maxLength": 50
                },

                "type": {
                    "type": "string",
                    "title": "Data Type",
                    "enum": [ "boolean", "currency", "date", "date_time", "duration", "email", "enum", "html", "password", "phone", "string", "text", "time", "url", "decimal", "int", "decimal_range", "int_range" ]
                },

                "revision": {
                    "type": "integer",
                    "title": "Revision",
                    "minimum": 0,
                    "default": 0
                },

                "units": {
                    "type": "string",
                    "title": "Unit Symbol",
                    "maxLength": 20
                },

                "weight": {
                    "type": "integer",
                    "title": "Order (Weight)",
                    "description": "Where in the list should this item show up priority wise.  Higher the number, higher on the list it will appear.",
                    "default": 0
                },

                "values": {
                    "type": "object",
                    "title": "Values",
                    "patternProperties": {
                        "^[a-z0-9_-]{1,50}$": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false
                },

                "meta": {
                    "type": "object",
                    "title": "Metadata",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            },
            "additionalProperties": false,
            "required": [ "name", "type" ]
        },

        "library-item": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "title": "Date",
                    "format": "date-time"
                },

                "name": {
                    "type": "string",
                    "title": "Name",
                    "minLength": 1,
                    "maxLength": 50
                },

                "type": {
                    "type": "string",
                    "title": "Item Type",
                    "minLength": 1,
                    "maxLength": 50,
                    "pattern": "^[a-z0-9_-]{1,50}$"
                },

                "revision": {
                    "type": "integer",
                    "title": "Revision",
                    "minimum": 0,
                    "default": 0
                },

                "tags": {
                    "type": "object",
                    "title": "Attributes Tags",
                    "patternProperties": {
                        "^[a-z0-9_-]{1,50}$": {
                            "anyOf": [
                                { "type": "string" },
                                {
                                    "type": "array",
                                    "items": {
                                        "type": "string",
                                        "minLength": 1,
                                        "maxLength": 50,
                                        "pattern": "^[a-z0-9_-]{1,50}$"
                                    }
                                }
                            ]
                        }
                    },
                    "additionalProperties": false
                },

                "items": {
                    "type": "object",
                    "title": "Attachments",
                    "patternProperties": {
                        "^[a-z0-9_-]{1,50}$": {
                            "$ref": "#/$defs/library-item"
                        }
                    },
                    "additionalProperties": false
                },

                "meta": {
                    "type": "object",
                    "title": "Metadata",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            },
            "additionalProperties": false,
            "required": [ "name", "type" ]
        },

        "library": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "title": "Key",
                    "minLength": 1,
                    "maxLength": 50,
                    "pattern": "^[a-z0-9_-]{1,50}$"
                },

                "name": {
                    "type": "string",
                    "title": "Name",
                    "minLength": 1,
                    "maxLength": 50
                },

                "revision": {
                    "type": "integer",
                    "title": "Revision",
                    "minimum": 0,
                    "default": 0
                },

                "types": {
                    "type": "object",
                    "title": "Item Types",
                    "patternProperties": {
                        "^[a-z0-9_-]{1,50}$": {
                            "$ref": "#/$defs/item-type"
                        }
                    },
                    "additionalProperties": false
                },

                "items": {
                    "type": "object",
                    "title": "Items",
                    "patternProperties": {
                        "^[a-z0-9_-]{1,50}$": {
                            "$ref": "#/$defs/library-item"
                        }
                    },
                    "additionalProperties": false
                },

                "meta": {
                    "type": "object",
                    "title": "Metadata",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            },
            "additionalProperties": false,
            "required": [ "types", "items" ]
        }
    },

    "$ref": "#/$defs/library"
}

=== things-library/Schemas/tests/ThingsLibrary.Schema.Tests/TestData/library/valid/basic.json
{
	"key": "test_library",
	"name": "Test Library",
	
	"types": {
		"test_type": {
			"name": "Test Type",
			"attributes": {
				"brand": {
					"name": "Brand",
					"type": "string"
				},
				"model": {
					"name": "Model",
					"type": "string"
				},
				"color": {
					"name": "Color",
					"type": "enum",
					"values": {
						"black": "Black",
						"red": "Red",
						"blue": "Blue"
					}
				}
			}
		}
	},

	"items": {
		"test_item": {			
			"name": "Test Item",
			"type": "test_type",
			"version": 1,
			"attributes": {
				"brand": "Test",
				"color": [ "red", "blue" ],
				"model": ""
			}
		}
	}
}
