=== things-library/Schemas/1.0/library.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://schema.thingslibrary.io/1.0/library.json",
    "$comment": "Libraries hold item types and items that have a type.",
    
    "$defs": {
        "item-type": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "title": "Key",
                    "minLength": 2,
                    "maxLength": 200,
                    "pattern": "^[a-z0-9_]*$"
                },

                "name": {
                    "type": "string",
                    "title": "Name",
                    "minLength": 2,
                    "maxLength": 200
                },

                "description": {
                    "type": "string",
                    "title": "Description"
                },

                "system": {
                    "type": "boolean",
                    "title": "System",
                    "description": "Indicates that this item type is managed by the system and can't be edited by a user",
                    "default": false
                },

                "locked": {
                    "type": "boolean",
                    "title": "Locked",
                    "description": "Prevent attachments from outside of the attachment listing",
                    "default": false
                },

                "attributes": {
                    "type": "array",
                    "title": "Attributes",
                    "items": {
                        "$ref": "#/$defs/item-type-attribute"
                    }
                },

                "attachments": {
                    "type": "array",
                    "title": "Attachments",
                    "items": {
                        "$ref": "#/$defs/item-type-attachment"
                    }
                },

                "metadata": {
                    "type": "object",
                    "title": "Metadata",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            },
            "additionalProperties": false,
            "required": [ "key", "name" ]
        },

        "item-type-attachment": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "title": "Type Key",
                    "minLength": 2,
                    "maxLength": 200,
                    "pattern": "^[a-z0-9_]*$"
                },

                "name": {
                    "type": "string",
                    "title": "Name",
                    "minLength": 2,
                    "maxLength": 200
                },

                "description": {
                    "type": "string",
                    "title": "Description"
                },

                "required": {
                    "type": "boolean",
                    "title": "Required",
                    "description": "Is this item type required to be attached?",
                    "default": false
                },

                "limit": {
                    "type": "integer",
                    "title": "Limit",
                    "description": "Limit number of attachments of this type? (0 = not limited)",
                    "default": 0
                },

                "metadata": {
                    "type": "object",
                    "title": "Metadata",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            },
            "required": [ "type", "name" ]
        },

        "item-type-attribute": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "title": "Key",
                    "minLength": 2,
                    "maxLength": 200,
                    "pattern": "^[a-z0-9_]*$"
                },

                "name": {
                    "type": "string",
                    "title": "Name",
                    "minLength": 2,
                    "maxLength": 200
                },

                "type": {
                    "type": "string",
                    "title": "Data Type",
                    "enum": [ "boolean", "currency", "date", "date_time", "duration", "email", "enum", "html", "password", "phone", "string", "text", "time", "url", "decimal", "int", "decimal_range", "int_range" ]
                },

                "units": {
                    "type": "string",
                    "title": "Unit Symbol",
                    "maxLength": 20
                },

                "weight": {
                    "type": "integer",
                    "title": "Order (Weight)",
                    "description": "Where in the list should this item show up priority wise.  Higher the number, higher on the list it will appear.",
                    "default": 0
                },

                "multi": {
                    "type": "boolean",
                    "title": "Allow Multiples",
                    "description": "Allow multiple of this attribute attached to a Thing",
                    "default": false
                },

                "required": {
                    "type": "boolean",
                    "title": "Required",
                    "description": "Is this field required to be entered",
                    "default": false
                },

                "locked": {
                    "type": "boolean",
                    "title": "Locked",
                    "description": "Prevent new attribute values from being added.",
                    "default": false
                },

                "system": {
                    "type": "boolean",
                    "title": "System",
                    "description": "Indicates that this attribute is managed by the system and can't be edited by a user.",
                    "default": false
                },

                "values": {
                    "type": "object",
                    "title": "Values",
                    "additionalProperties": {
                        "type": "string"
                    }
                },

                "metadata": {
                    "type": "object",
                    "title": "Metadata",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            },
            "required": [ "key", "name", "type" ]
        },

        "item": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "title": "Key",
                    "minLength": 2,
                    "maxLength": 200,
                    "pattern": "^[a-z0-9_\\-]*$"
                },

                "date": {
                    "type": "string",
                    "title": "Date",
                    "format": "date-time"
                },

                "name": {
                    "type": "string",
                    "title": "Name",
                    "minLength": 2,
                    "maxLength": 200
                },

                "type": {
                    "type": "string",
                    "title": "Type",
                    "minLength": 2,
                    "maxLength": 200,
                    "pattern": "^[a-z0-9_]*$"
                },

                "attributes": {
                    "type": "object",
                    "title": "Attributes",
                    "patternProperties": {
                        "^[a-z0-9_]+$": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false
                },

                "attachments": {
                    "type": "array",
                    "title": "Attachments",
                    "items": {
                        "$ref": "#/$defs/item"
                    }
                },

                "metadata": {
                    "type": "object",
                    "title": "Metadata",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            },
            "required": [ "key", "name", "type" ]
        }
    },

    "type": "object",
    "properties": {
        "key": {
            "type": "string",
            "title": "Key",
            "minLength": 5,
            "maxLength": 200,
            "pattern": "^[a-z0-9_\\-]*$"
        },

        "name": {
            "type": "string",
            "title": "Name",
            "minLength": 5,
            "maxLength": 200
        },

        "types": {
            "type": "array",
            "title": "Item Types",
            "items": {
                "$ref": "#/$defs/item-type"
            }
        },

        "items": {
            "type": "array",
            "title": "Things",
            "items": {
                "$ref": "#/$defs/item"
            }
        },

        "metadata": {
            "type": "object",
            "title": "Metadata",
            "additionalProperties": {
                "type": "string"
            }
        }
    },
    "required": [ "key", "name" ]
}

=== things-library/Schemas/tests/ThingsLibrary.Schema.Tests/TestData/library/valid/library_movies.json
{
	"key": "movies",
	"name": "Bluray Movies",

	"types": [
		{ 
			"key":"movie",
			"name": "Movie",
			"attributes": [
				{	"key": "year", "name": "Year", "type": "enum", "units": "", "weight": 10 },
				{	"key": "genre", "name": "Genre", "type": "enum", "units": "", "weight": 9 },
				{	"key": "director",	"name": "Director",	"type": "enum",	"units": "", "weight": 8 },
				{	"key": "aspect_ratio", "name": "Aspect Ratio", "type": "string", "units": "", "weight": 7 },
				{	"key": "run_time", "name": "Run Time", "type": "string", "units": "minutes", "weight": 6 },
				{	"key": "box_office", "name": "Box Office", "type": "currency", "units": "million", "weight": 5 },
				{	"key": "budget", "name": "Budget", "type": "currency", "units": "million", "weight": 4 },
				{	"key": "upc", "name": "UPC", "type": "string", "units": "", "weight": 3 }
			]
		}
	],

	"items": [
		{
			"key": "2010_inception",
			"name": "Inception (2010)",
			"type": "movie",
			"attributes": {
				"year": "2010",
				"genre": "Sci-Fi",
				"director": "Christopher Nolan",
				"box_office": "829.9",
				"budget": "160",
				"upc": "123456789012",
				"aspect_ratio": "2.39:1",
				"run_time": "148"
			}
		},
		{
			"key": "1994_shawshank_redemption",
			"name": "The Shawshank Redemption (1994)",
			"type": "movie",
			"attributes": {
				"year": "1994",
				"genre": "Drama",
				"director": "Frank Darabont",
				"box_office": "",
				"budget": "25",
				"upc": "234567890123",
				"aspect_ratio": "1.85:1",
				"run_time": "142"
			}
		},
		{
			"key": "2008_the_dark_knight",
			"name": "Batman: The Dark Knight(2008)",
			"type": "movie",
			"attributes": {
				"year": "2008",
				"genre": "Action",
				"director": "Christopher Nolan",
				"box_office": "1,004",
				"budget": "185",
				"upc": "345678901234",
				"aspect_ratio": "2.39:1",
				"run_time": "152"
			}
		},
		{
			"key": "1994_pulp_fiction",
			"name": "Pulp Fiction (1994)",
			"type": "movie",
			"attributes": {
				"year": "1994",
				"genre": "Crime",
				"director": "Quentin Tarantino",
				"box_office": "213.9",
				"budget": "8",
				"upc": "456789012345",
				"aspect_ratio": "2.39:1",
				"run_time": "154"
			}
		},
		{
			"key": "1972_the_godfather",
			"name": "The Godfather (1972)",
			"type": "movie",
			"attributes": {
				"year": "1972",
				"genre": "Crime",
				"director": "Francis Ford Coppola",
				"box_office": "250",
				"budget": "6",
				"upc": "567890123456",
				"aspect_ratio": "1.85:1",
				"run_time": "175"
			}
		}
	]
}

=== things-library/Schemas/tests/ThingsLibrary.Schema.Tests/TestData/library/valid/library_schema_missing.json
{	
	"key": "test_basic",
	"name": "Basic Valid Test",
	
	"types": [
		{
			"key": "test_type",
			"name": "Test Type",
			"attributes": [
				{ "key": "location", "name": "Location", "type": "enum", "values": { 
					  "location_a":"Location A", 
					  "location_b": "Location B"
				}},
				{ "key": "last_name", "name":  "Last Name", "type":  "string" }
			]
		}
	],

	"items": [
		{ 
			"key": "test_thing",
			"name":  "Test Thing",
			"type":  "test-type",
			"attributes": {
				"location":  "basement",
				"last_name": "Last Name"
			}
		}

	]
}

=== things-library/Schemas/tests/ThingsLibrary.Schema.Tests/TestData/library/valid/library_users.json
{	
	"key": "system_users",
	"name": "System Users",
	
	"types": [		
		{ 
			"key": "person",            			
            "name": "Person",
            "attributes": [
				{ "key": "given_name", "name": "First Name", "type": "string", "weight": 9 }, 
				{ "key": "family_name", "name": "Last Name", "type": "string", "weight": 8 }, 
				{ "key": "email", "name": "Email Address", "type": "email", "required": true, "weight": 7 }, 
				{ "key": "phone", "name": "Phone Number", "type": "phone", "weight": 6 }, 
				{ "key": "birth_date", "name": "Birth Date", "type": "date", "weight": 5 }
            ]
		}
	],

	"items": [
		{ 
			"key": "sgamgee_shire_com",				
			"name": "sgamgee@shire.com",
			"type": "person",
			"attributes": {
				"given_name": "Sam",
				"family_name": "Gamgee",
				"email": "sgamgee@shire.com",
				"phone": "515-555-5827"
			}			
		},
		{ 
			"key": "ohunter_shire_org",				
			"name": "ohunter@shire.org",
			"type": "person",
			"attributes": {
				"given_name": "Orc",
				"family_name": "Hunter",
				"email": "ohunter@shire.org",
				"phone": "515-555-2712"
			}
		}, 
		{
			"key": "fbaggins_shire_org",					
			"name": "fbaggins@shire.org",
			"type": "person",
			"attributes": {
				"given_name": "Frodo",
				"family_name": "Baggins",
				"email": "fbaggins@shire.org",
				"phone": "515-555-0721"
			}
		},
		{ 
			"key": "ggray_shire_org",				
			"name": "ggray@shire.org",
			"type": "person",
			"attributes": {
				"given_name": "Gandalf",
				"family_name": "Gray",
				"email": "ggray@shire.org"
			}
		}
	]
}
